name: pguide
channels:
- defaults
dependencies:
- beautifulsoup4=4.6.0
- html5lib=0.999999999
- pytest=3.3.0
- python=3.6.3
- requests=2.18.4
- pip:
  - imdbpy>=6.2
  - lxml==4.1.1
  - textwrap3==0.9.1
